!obj:pylearn2.cross_validation.Train {
    dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
        path: './data/train-pylearn2.csv',
        task: 'classification',
    },
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 1024,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 1024,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: 1024,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h3',
                     dim: 1024,
                     sparse_init: 15,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     n_classes: 9,
                     irange: 0.
                 }
                ],
        nvis: 93,

    },
    algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
        batch_size: 10000,
        line_search_mode: 'exhaustive',
        conjugate: 1,
        updates_per_batch: 10,
        monitoring_dataset: {
            'train' : *train
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "train_y_misclass"
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 10
                }
            ]
        }
    },
    save_path: './submission/pylearn2-nn/pylearn2-nn.pkl',
}
